In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/spaceship-titanic/sample_submission.csv
/kaggle/input/spaceship-titanic/train.csv
/kaggle/input/spaceship-titanic/test.csv

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("/kaggle/input/spaceship-titanic/train.csv")

In [4]:
test = pd.read_csv("/kaggle/input/spaceship-titanic/test.csv")

# Предобработка данных

In [5]:
y = df["Transported"]

In [6]:
df.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [7]:
test.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
0,0013_01,Earth,True,G/3/S,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0,Nelly Carsoning
1,0018_01,Earth,False,F/4/S,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0,Lerome Peckers
2,0019_01,Europa,True,C/0/S,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0,Sabih Unhearfus
3,0021_01,Europa,False,C/1/S,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0,Meratz Caltilter
4,0023_01,Earth,False,F/5/S,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0,Brence Harperez

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   object
 1   HomePlanet    8492 non-null   object
 2   CryoSleep     8476 non-null   object
 3   Cabin         8494 non-null   object
 4   Destination   8511 non-null   object
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   object
 13  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(7)
memory usage: 891.5+ KB

In [9]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4277 entries, 0 to 4276
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   4277 non-null   object
 1   HomePlanet    4190 non-null   object
 2   CryoSleep     4184 non-null   object
 3   Cabin         4177 non-null   object
 4   Destination   4185 non-null   object
 5   Age           4186 non-null   float64
 6   VIP           4184 non-null   object
 7   RoomService   4195 non-null   float64
 8   FoodCourt     4171 non-null   float64
 9   ShoppingMall  4179 non-null   float64
 10  Spa           4176 non-null   float64
 11  VRDeck        4197 non-null   float64
 12  Name          4183 non-null   object
dtypes: float64(6), object(7)
memory usage: 434.5+ KB

In [10]:
df.isna().any()

PassengerId     False
HomePlanet       True
CryoSleep        True
Cabin            True
Destination      True
Age              True
VIP              True
RoomService      True
FoodCourt        True
ShoppingMall     True
Spa              True
VRDeck           True
Name             True
Transported     False
dtype: bool

In [11]:
test.isna().any()

PassengerId     False
HomePlanet       True
CryoSleep        True
Cabin            True
Destination      True
Age              True
VIP              True
RoomService      True
FoodCourt        True
ShoppingMall     True
Spa              True
VRDeck           True
Name             True
dtype: bool

In [12]:
df.describe()

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
count,8514.000000,8512.000000,8510.000000,8485.000000,8510.000000,8505.000000
mean,28.827930,224.687617,458.077203,173.729169,311.138778,304.854791
std,14.489021,666.717663,1611.489240,604.696458,1136.705535,1145.717189
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,19.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,38.000000,47.000000,76.000000,27.000000,59.000000,46.000000
max,79.000000,14327.000000,29813.000000,23492.000000,22408.000000,24133.000000

In [13]:
missing = pd.DataFrame({
    "dtype": df.dtypes,
    "missing_count": df.isna().sum(),
    "missing_pct": df.isna().mean() * 100  # % пропусков
})

missing = missing[missing["missing_count"] > 0]
missing.sort_values(by="missing_count", ascending=False)

                dtype  missing_count  missing_pct
CryoSleep      object            217     2.496261
ShoppingMall  float64            208     2.392730
VIP            object            203     2.335212
HomePlanet     object            201     2.312205
Name           object            200     2.300702
Cabin          object            199     2.289198
VRDeck        float64            188     2.162660
FoodCourt     float64            183     2.105142
Spa           float64            183     2.105142
Destination    object            182     2.093639
RoomService   float64            181     2.082135
Age           float64            179     2.059128

In [14]:
missing = pd.DataFrame({
    "dtype": test.dtypes,
    "missing_count": test.isna().sum(),
    "missing_pct": test.isna().mean() * 100  # % пропусков
})

missing = missing[missing["missing_count"] > 0]
missing.sort_values(by="missing_count", ascending=False)

                dtype  missing_count  missing_pct
FoodCourt     float64            106     2.478373
Spa           float64            101     2.361468
Cabin          object            100     2.338087
ShoppingMall  float64             98     2.291326
Name           object             94     2.197802
CryoSleep      object             93     2.174421
VIP            object             93     2.174421
Destination    object             92     2.151040
Age           float64             91     2.127660
HomePlanet     object             87     2.034136
RoomService   float64             82     1.917232
VRDeck        float64             80     1.870470

In [15]:
# Категориальные признаки
cat_cols = ['CryoSleep', 'VIP', 'HomePlanet', "Name", "Cabin", 'Destination']
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

/tmp/ipykernel_13/384164441.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col] = df[col].fillna(df[col].mode()[0])

In [16]:
cat_cols = ['CryoSleep', 'VIP', 'HomePlanet', "Name", "Cabin", 'Destination']
for col in cat_cols:
    test[col] = test[col].fillna(test[col].mode()[0])

/tmp/ipykernel_13/4004439204.py:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  test[col] = test[col].fillna(test[col].mode()[0])

In [17]:
# Числовые признаки
num_cols = ['ShoppingMall', 'VRDeck', 'FoodCourt', 'Spa', 'RoomService', 'Age']
for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

In [18]:
# Числовые признаки
num_cols = ['ShoppingMall', 'VRDeck', 'FoodCourt', 'Spa', 'RoomService', 'Age']
for col in num_cols:
    test[col] = test[col].fillna(test[col].median())

## One hot кодирование

In [19]:
object_cols = df.select_dtypes(include=['object']).columns
print(object_cols)

Index(['PassengerId', 'HomePlanet', 'Cabin', 'Destination', 'Name'], dtype='object')

In [20]:
object_cols = test.select_dtypes(include=['object']).columns
print(object_cols)

Index(['PassengerId', 'HomePlanet', 'Cabin', 'Destination', 'Name'], dtype='object')

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   object
 1   HomePlanet    8693 non-null   object
 2   CryoSleep     8693 non-null   bool
 3   Cabin         8693 non-null   object
 4   Destination   8693 non-null   object
 5   Age           8693 non-null   float64
 6   VIP           8693 non-null   bool
 7   RoomService   8693 non-null   float64
 8   FoodCourt     8693 non-null   float64
 9   ShoppingMall  8693 non-null   float64
 10  Spa           8693 non-null   float64
 11  VRDeck        8693 non-null   float64
 12  Name          8693 non-null   object
 13  Transported   8693 non-null   bool
dtypes: bool(3), float64(6), object(5)
memory usage: 772.7+ KB

In [22]:
df.shape

(8693, 14)

In [23]:
df[object_cols].nunique()

PassengerId    8693
HomePlanet        3
Cabin          6560
Destination       3
Name           8473
dtype: int64

In [24]:
test[object_cols].nunique()

PassengerId    4277
HomePlanet        3
Cabin          3265
Destination       3
Name           4176
dtype: int64

In [25]:
df

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,9276_01,Europa,False,A/98/P,55 Cancri e,41.0,True,0.0,6819.0,0.0,1643.0,74.0,Gravior Noxnuther,False
8689,9278_01,Earth,True,G/1499/S,PSO J318.5-22,18.0,False,0.0,0.0,0.0,0.0,0.0,Kurta Mondalley,False
8690,9279_01,Earth,False,G/1500/S,TRAPPIST-1e,26.0,False,0.0,0.0,1872.0,1.0,0.0,Fayey Connon,True
8691,9280_01,Europa,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre,False
8692,9280_02,Europa,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre,True

In [26]:
df["GroupId"] = df["PassengerId"].str.split('_').str[0]

In [27]:
test["GroupId"] = test["PassengerId"].str.split('_').str[0]

In [28]:
df.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported,GroupId
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False,0001
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True,0002
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False,0003
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False,0003
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True,0004

In [29]:
group_freq = df['GroupId'].value_counts() / len(df)
df['GroupId_freq'] = df['GroupId'].map(group_freq)
df = df.drop(columns=['GroupId'])

In [30]:
group_freq = test['GroupId'].value_counts() / len(test)
test['GroupId_freq'] = test['GroupId'].map(group_freq)
test = test.drop(columns=['GroupId'])

In [31]:
df.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported,GroupId_freq
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False,0.000115
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True,0.000115
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False,0.000230
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False,0.000230
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True,0.000115

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   object
 1   HomePlanet    8693 non-null   object
 2   CryoSleep     8693 non-null   bool
 3   Cabin         8693 non-null   object
 4   Destination   8693 non-null   object
 5   Age           8693 non-null   float64
 6   VIP           8693 non-null   bool
 7   RoomService   8693 non-null   float64
 8   FoodCourt     8693 non-null   float64
 9   ShoppingMall  8693 non-null   float64
 10  Spa           8693 non-null   float64
 11  VRDeck        8693 non-null   float64
 12  Name          8693 non-null   object
 13  Transported   8693 non-null   bool
 14  GroupId_freq  8693 non-null   float64
dtypes: bool(3), float64(7), object(5)
memory usage: 840.6+ KB

In [33]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4277 entries, 0 to 4276
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   4277 non-null   object
 1   HomePlanet    4277 non-null   object
 2   CryoSleep     4277 non-null   bool
 3   Cabin         4277 non-null   object
 4   Destination   4277 non-null   object
 5   Age           4277 non-null   float64
 6   VIP           4277 non-null   bool
 7   RoomService   4277 non-null   float64
 8   FoodCourt     4277 non-null   float64
 9   ShoppingMall  4277 non-null   float64
 10  Spa           4277 non-null   float64
 11  VRDeck        4277 non-null   float64
 12  Name          4277 non-null   object
 13  GroupId_freq  4277 non-null   float64
dtypes: bool(2), float64(7), object(5)
memory usage: 409.5+ KB

In [34]:
df = df.drop(columns="PassengerId")

In [35]:
test = test.drop(columns="PassengerId")

In [36]:
df["Surname"] = df["Name"].str.split().str[1]

In [37]:
test["Surname"] = test["Name"].str.split().str[1]

In [38]:
df["Surname"].nunique()

2217

In [39]:
df['FamilySize'] = df.groupby('Surname')['Name'].transform('count')

In [40]:
test['FamilySize'] = test.groupby('Surname')['Name'].transform('count')

In [41]:
df.head()

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported,GroupId_freq,Surname,FamilySize
0,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False,0.000115,Ofracculy,1
1,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True,0.000115,Vines,4
2,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False,0.000230,Susent,6
3,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False,0.000230,Susent,6
4,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True,0.000115,Santantines,6

In [42]:
df = df.drop(columns=["Surname", "Name"])

In [43]:
test = test.drop(columns=["Surname", "Name"])

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   HomePlanet    8693 non-null   object
 1   CryoSleep     8693 non-null   bool
 2   Cabin         8693 non-null   object
 3   Destination   8693 non-null   object
 4   Age           8693 non-null   float64
 5   VIP           8693 non-null   bool
 6   RoomService   8693 non-null   float64
 7   FoodCourt     8693 non-null   float64
 8   ShoppingMall  8693 non-null   float64
 9   Spa           8693 non-null   float64
 10  VRDeck        8693 non-null   float64
 11  Transported   8693 non-null   bool
 12  GroupId_freq  8693 non-null   float64
 13  FamilySize    8693 non-null   int64
dtypes: bool(3), float64(7), int64(1), object(3)
memory usage: 772.7+ KB

In [45]:
# Разбиваю категориальный признак Cabin на 3 признака, чтобы уменьшить кол-во уникальных значений
df[["Deck", "CabinNum", "Side"]] = df["Cabin"].str.split('/', expand = True)

In [46]:
# Разбиваю категориальный признак Cabin на 3 признака, чтобы уменьшить кол-во уникальных значений
test[["Deck", "CabinNum", "Side"]] = test["Cabin"].str.split('/', expand = True)

In [47]:
df.head()

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,GroupId_freq,FamilySize,Deck,CabinNum,Side
0,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,False,0.000115,1,B,0,P
1,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,True,0.000115,4,F,0,S
2,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False,0.000230,6,A,0,S
3,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False,0.000230,6,A,0,S
4,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,True,0.000115,6,F,1,S

In [48]:
test.head()

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,GroupId_freq,FamilySize,Deck,CabinNum,Side
0,Earth,True,G/3/S,TRAPPIST-1e,27.0,False,0.0,0.0,0.0,0.0,0.0,0.000234,4,G,3,S
1,Earth,False,F/4/S,TRAPPIST-1e,19.0,False,0.0,9.0,0.0,2823.0,0.0,0.000234,1,F,4,S
2,Europa,True,C/0/S,55 Cancri e,31.0,False,0.0,0.0,0.0,0.0,0.0,0.000234,1,C,0,S
3,Europa,False,C/1/S,TRAPPIST-1e,38.0,False,0.0,6652.0,0.0,181.0,585.0,0.000234,1,C,1,S
4,Earth,False,F/5/S,TRAPPIST-1e,20.0,False,10.0,0.0,635.0,0.0,0.0,0.000234,3,F,5,S

In [49]:
df['Deck'].nunique()

8

In [50]:
df["CabinNum"].nunique()

1817

In [51]:
df["CabinNum"].dtypes

dtype('O')

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   HomePlanet    8693 non-null   object
 1   CryoSleep     8693 non-null   bool
 2   Cabin         8693 non-null   object
 3   Destination   8693 non-null   object
 4   Age           8693 non-null   float64
 5   VIP           8693 non-null   bool
 6   RoomService   8693 non-null   float64
 7   FoodCourt     8693 non-null   float64
 8   ShoppingMall  8693 non-null   float64
 9   Spa           8693 non-null   float64
 10  VRDeck        8693 non-null   float64
 11  Transported   8693 non-null   bool
 12  GroupId_freq  8693 non-null   float64
 13  FamilySize    8693 non-null   int64
 14  Deck          8693 non-null   object
 15  CabinNum      8693 non-null   object
 16  Side          8693 non-null   object
dtypes: bool(3), float64(7), int64(1), object(6)
memory usage: 976.4+ KB

In [53]:
df["CabinNum"] = df["CabinNum"].astype(int)

In [54]:
test["CabinNum"] = test["CabinNum"].astype(int)

In [55]:
df["Side"].nunique()

2

In [56]:
df = df.drop(columns=["Cabin"])

In [57]:
test = test.drop(columns=["Cabin"])

In [58]:
one_hot_cols = df.select_dtypes(include=['object']).columns
print(one_hot_cols)

Index(['HomePlanet', 'Destination', 'Deck', 'Side'], dtype='object')

In [59]:
df[one_hot_cols].nunique()

HomePlanet     3
Destination    3
Deck           8
Side           2
dtype: int64

In [60]:
df = pd.get_dummies(df, one_hot_cols, drop_first = True)

In [61]:
test = pd.get_dummies(test, one_hot_cols, drop_first = True)

In [62]:
df.head()

,CryoSleep,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,GroupId_freq,...,Destination_PSO J318.5-22,Destination_TRAPPIST-1e,Deck_B,Deck_C,Deck_D,Deck_E,Deck_F,Deck_G,Deck_T,Side_S
0,False,39.0,False,0.0,0.0,0.0,0.0,0.0,False,0.000115,...,False,True,True,False,False,False,False,False,False,False
1,False,24.0,False,109.0,9.0,25.0,549.0,44.0,True,0.000115,...,False,True,False,False,False,False,True,False,False,True
2,False,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False,0.000230,...,False,True,False,False,False,False,False,False,False,True
3,False,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False,0.000230,...,False,True,False,False,False,False,False,False,False,True
4,False,16.0,False,303.0,70.0,151.0,565.0,2.0,True,0.000115,...,False,True,False,False,False,False,True,False,False,True

In [63]:
df.isnull().sum()

CryoSleep                    0
Age                          0
VIP                          0
RoomService                  0
FoodCourt                    0
ShoppingMall                 0
Spa                          0
VRDeck                       0
Transported                  0
GroupId_freq                 0
FamilySize                   0
CabinNum                     0
HomePlanet_Europa            0
HomePlanet_Mars              0
Destination_PSO J318.5-22    0
Destination_TRAPPIST-1e      0
Deck_B                       0
Deck_C                       0
Deck_D                       0
Deck_E                       0
Deck_F                       0
Deck_G                       0
Deck_T                       0
Side_S                       0
dtype: int64

In [64]:
test.isnull().sum()

CryoSleep                    0
Age                          0
VIP                          0
RoomService                  0
FoodCourt                    0
ShoppingMall                 0
Spa                          0
VRDeck                       0
GroupId_freq                 0
FamilySize                   0
CabinNum                     0
HomePlanet_Europa            0
HomePlanet_Mars              0
Destination_PSO J318.5-22    0
Destination_TRAPPIST-1e      0
Deck_B                       0
Deck_C                       0
Deck_D                       0
Deck_E                       0
Deck_F                       0
Deck_G                       0
Deck_T                       0
Side_S                       0
dtype: int64

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 24 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   CryoSleep                  8693 non-null   bool
 1   Age                        8693 non-null   float64
 2   VIP                        8693 non-null   bool
 3   RoomService                8693 non-null   float64
 4   FoodCourt                  8693 non-null   float64
 5   ShoppingMall               8693 non-null   float64
 6   Spa                        8693 non-null   float64
 7   VRDeck                     8693 non-null   float64
 8   Transported                8693 non-null   bool
 9   GroupId_freq               8693 non-null   float64
 10  FamilySize                 8693 non-null   int64
 11  CabinNum                   8693 non-null   int64
 12  HomePlanet_Europa          8693 non-null   bool
 13  HomePlanet_Mars            8693 non-null   bool
 14  Destination_PSO J318.5-22  8693 non-null   bool
 15  Destination_TRAPPIST-1e    8693 non-null   bool
 16  Deck_B                     8693 non-null   bool
 17  Deck_C                     8693 non-null   bool
 18  Deck_D                     8693 non-null   bool
 19  Deck_E                     8693 non-null   bool
 20  Deck_F                     8693 non-null   bool
 21  Deck_G                     8693 non-null   bool
 22  Deck_T                     8693 non-null   bool
 23  Side_S                     8693 non-null   bool
dtypes: bool(15), float64(7), int64(2)
memory usage: 738.7 KB

# Обучение модели

In [66]:
X = df.drop(columns=['Transported'])

In [67]:
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score, KFold
import numpy as np

# --- Определяем базовые модели ---
base_models = [
    ('rf', RandomForestClassifier(n_estimators=50, random_state=42)),
    ('gb', GradientBoostingClassifier(n_estimators=50, random_state=42))
]

# --- Определяем мета-модель ---
meta_model = LogisticRegression()

# --- Стек-модель с k-fold ---
stacking_model = StackingClassifier(
    estimators=base_models,
    final_estimator=meta_model,
    cv=KFold(n_splits=3, shuffle=True, random_state=42)  # здесь k-fold
)

# --- Оценка модели через k-fold ---
scores = cross_val_score(stacking_model, X, y, cv=KFold(n_splits=3, shuffle=True, random_state=42), scoring='accuracy')
print("Средняя точность:", np.mean(scores))

Средняя точность: 0.8039806455183682

In [68]:
# --- Финальное обучение ---
stacking_model.fit(X, y)

# --- Предсказание ---
y_test_pred = stacking_model.predict(test)

In [69]:
sample_submission = pd.read_csv("/kaggle/input/spaceship-titanic/sample_submission.csv")

In [70]:
submission = pd.DataFrame({
    "PassengerId": sample_submission["PassengerId"],
    "Transported": y_test_pred.astype(bool)
})
submission.to_csv("submission.csv", index=False)